# Basic linear algebra concepts 

## notebook jw_gda_1_linearalgebra

In [1]:
import numpy as np
import numpy.linalg as linalg

## Properties of matrix multiplication 

In [2]:
m=5
p=3
n=4
a=np.random.rand(m,p)
b=np.random.rand(p,n)
print(a)

[[0.62717602 0.76930566 0.63285537]
 [0.36702086 0.94158038 0.09727539]
 [0.49668758 0.51799662 0.74023796]
 [0.51538139 0.58456042 0.88796809]
 [0.84169362 0.47120899 0.86695241]]


In [3]:
# must be conformable for matrix multiplication
c=np.dot(a,b)
c.shape

(5, 4)

In [55]:
# if you switch the order it won't work - the order b*a is not conformable
np.dot(b,a)

ValueError: shapes (3,4) and (5,3) not aligned: 4 (dim 1) != 5 (dim 0)

#### The transpose of the product of matrices (AB)^T is B^TA^T

In [56]:
np.dot(a,b).T

array([[0.72009634, 0.10068032, 0.60878984, 1.07187756, 0.95391731],
       [0.70698599, 0.52342117, 1.0977857 , 1.08170632, 1.10159322],
       [0.82472722, 0.6176212 , 1.36375803, 1.2254758 , 1.26052265],
       [0.57309304, 0.17334326, 0.75605049, 0.77986127, 0.73651802]])

In [57]:
np.dot(b.T,a.T)

array([[0.72009634, 0.10068032, 0.60878984, 1.07187756, 0.95391731],
       [0.70698599, 0.52342117, 1.0977857 , 1.08170632, 1.10159322],
       [0.82472722, 0.6176212 , 1.36375803, 1.2254758 , 1.26052265],
       [0.57309304, 0.17334326, 0.75605049, 0.77986127, 0.73651802]])

#### Square matrices are always comformable, but matrix multiplication is not commutative

In [58]:
d1=np.random.rand(p,p)
d2=np.random.rand(p,p)

In [59]:
np.dot(d1,d2)

array([[1.29717129, 1.08332123, 0.78110125],
       [0.96789809, 0.69470739, 0.50586284],
       [1.16367622, 0.89487514, 0.62995161]])

In [60]:
np.dot(d2,d1)

array([[0.56294486, 0.64287761, 0.9698147 ],
       [0.93467857, 0.86719973, 1.35203452],
       [0.80670302, 0.7865687 , 1.19168569]])

#### Make a simple data matrix and perform some basic operations

In [61]:
# each column is e.g. a time series of m time values, and there are n observation locations
m=10
n=4
d=np.random.rand(m,n)

In [62]:
# the mean of each time series
d.mean(axis=0)

array([0.4079037 , 0.45419148, 0.4202574 , 0.6090462 ])

In [63]:
# the mean of all observations at each time
d.mean(axis=1)

array([0.33582652, 0.47532706, 0.10843199, 0.84498934, 0.48391   ,
       0.47438013, 0.57714791, 0.47716002, 0.66594417, 0.28537981])

#### Calculate the covariance matrix C = D'D

In [64]:
# but first remove the mean from each time series
dd=d-d.mean(axis=0)

In [65]:
# check
dd.mean(axis=0)

array([-4.44089210e-17, -3.33066907e-17, -5.55111512e-17,  3.33066907e-17])

In [66]:
# then variance of each time series is the diagonal of 1/m * d.T*d (remember to divide by the number of points, m)
# pay attention to whether it is d.T*d or d*d.T
cov=np.dot(dd.T,dd)/m
print(cov.diagonal())

[0.06382473 0.08849275 0.06191792 0.06520133]


In [67]:
# compare to using the built-in function
d.var(axis=0)

array([0.06382473, 0.08849275, 0.06191792, 0.06520133])

In [68]:
# we got the same result, which tells us something about the assumed dof 
# the default os ddof=0 in python which is differetn from MATLAB
d.var(axis=0,ddof=0)

array([0.06382473, 0.08849275, 0.06191792, 0.06520133])

In [69]:
d.var(axis=0,ddof=1)

array([0.07091637, 0.09832528, 0.06879768, 0.07244593])

In [70]:
# check
(np.dot(dd.T,dd)/(m-1)).diagonal()

array([0.07091637, 0.09832528, 0.06879768, 0.07244593])

## Projecting a vector onto an orthogonal basis set

#### Compute eigenvectors of a matrix

In [71]:
# remember we did this to shorten the syntax numpy.linalg.eig in the code that follows
# import numpy.linalg as linalg

In [73]:
# make a random square matrix of dimension n and find its eigenvectors
n=5;
a=np.random.rand(n,n)
eigvals,eigvecs=linalg.eig(a)
eigvecs

array([[-0.42492943+0.j        ,  0.01621648+0.j        ,
         0.69733639+0.j        ,  0.06424386+0.01243828j,
         0.06424386-0.01243828j],
       [-0.45322557+0.j        , -0.15298705+0.j        ,
        -0.52615536+0.j        ,  0.33896565+0.40350909j,
         0.33896565-0.40350909j],
       [-0.478855  +0.j        , -0.18012892+0.j        ,
        -0.19696354+0.j        , -0.61522551+0.j        ,
        -0.61522551-0.j        ],
       [-0.29871045+0.j        , -0.62917351+0.j        ,
        -0.39254294+0.j        ,  0.28058055-0.50997343j,
         0.28058055+0.50997343j],
       [-0.54359131+0.j        ,  0.74028795+0.j        ,
         0.20975676+0.j        ,  0.02155214+0.01534461j,
         0.02155214-0.01534461j]])

In [74]:
# make a random SYMMETRIC square matrix of dimension n and find its eigenvectors
c=np.dot(a,a.T);
eigvals,eigvecs=linalg.eig(c)
eigvecs

array([[-0.41254268, -0.15114579,  0.68340855, -0.3328512 ,  0.47867142],
       [-0.4571753 ,  0.42436657,  0.04087453, -0.45459826, -0.63448676],
       [-0.49308011, -0.46969699,  0.15997641,  0.60425569, -0.38149619],
       [-0.30670097,  0.72382563, -0.0026151 ,  0.52199929,  0.33093938],
       [-0.53254653, -0.22919239, -0.71111373, -0.211996  ,  0.33651152]])

In [75]:
# the eigenvalues (and eigenvectors) of of a real symmetric matrix are always real
eigvals

array([7.33184949, 1.03409974, 0.02426052, 0.34574908, 0.23780187])

In [76]:
# numpy does not return the eigenvalues in any particular order, so sort them in descending order
# from largest to smallest
order = np.flip(eigvals.argsort())
order

array([0, 1, 3, 4, 2])

In [77]:
eigvals=eigvals[order]
eigvecs=eigvecs[:,order]
print(eigvals)
print(eigvecs)

[7.33184949 1.03409974 0.34574908 0.23780187 0.02426052]
[[-0.41254268 -0.15114579 -0.3328512   0.47867142  0.68340855]
 [-0.4571753   0.42436657 -0.45459826 -0.63448676  0.04087453]
 [-0.49308011 -0.46969699  0.60425569 -0.38149619  0.15997641]
 [-0.30670097  0.72382563  0.52199929  0.33093938 -0.0026151 ]
 [-0.53254653 -0.22919239 -0.211996    0.33651152 -0.71111373]]


In [79]:
# use a loop to take inner product of first eigenvector with all the others 
for i in np.arange(len(eigvals)):
    innerprod=np.dot(eigvecs[:,0].T,eigvecs[:,i])
    print(innerprod)

0.9999999999999999
-4.3322455805065386e-17
-6.94033171408641e-17
3.09394000707777e-17
-1.3720006158425484e-16


In [80]:
# the eigenvectors are a spanning (or basis) set so that any vector can be projected onto the basis set, i.e., 
# expressed as a linear weighted sum of the basis vectors

In [81]:
# make a random vector,f
f=np.random.rand(n,1)
f

array([[0.24112461],
       [0.11243983],
       [0.09667273],
       [0.19998163],
       [0.69067789]])

In [82]:
# project f onto just one of th eigenvectors
np.dot(eigvecs[:,3].T,f)

array([0.30580046])

In [83]:
# project on to ALL the vector in one matrix multiplication
A=np.dot(eigvecs.T,f)
A

array([[-0.62769898],
       [-0.04768244],
       [-0.1149892 ],
       [ 0.30580046],
       [-0.3068256 ]])

In [84]:
# notice this does not use the inverse matrix, but works with a simple transpose because eigvecs.T is its own inverse
misfit=eigvecs.T-linalg.inv(eigvecs)
misfit

array([[ 1.11022302e-16,  5.55111512e-17,  5.55111512e-17,
        -1.11022302e-16,  1.11022302e-16],
       [-5.55111512e-17,  2.22044605e-16, -2.22044605e-16,
         0.00000000e+00,  2.49800181e-16],
       [ 7.77156117e-16, -3.33066907e-16, -2.22044605e-16,
        -1.11022302e-16,  8.32667268e-17],
       [ 1.33226763e-15, -2.22044605e-16,  9.43689571e-16,
         1.66533454e-16, -2.05391260e-15],
       [ 1.11022302e-15, -1.88737914e-15, -4.99600361e-16,
         8.85142654e-16,  8.88178420e-16]])

In [85]:
# also, if the transpose is the inverse, then e.T*e should be I
tmp=np.dot(eigvecs.T,eigvecs)
print(tmp)

[[ 1.00000000e+00 -5.72002436e-17 -8.32811049e-17  3.09394001e-17
  -8.16889104e-17]
 [-5.72002436e-17  1.00000000e+00 -2.88928433e-16 -1.89423187e-16
  -2.98157014e-16]
 [-8.32811049e-17 -2.88928433e-16  1.00000000e+00  8.38416750e-16
   4.68879974e-16]
 [ 3.09394001e-17 -1.89423187e-16  8.38416750e-16  1.00000000e+00
   2.49338746e-15]
 [-8.16889104e-17 -2.98157014e-16  4.68879974e-16  2.49338746e-15
   1.00000000e+00]]


In [86]:
# check that the vector of weights, A, times the eigenvectors, gives us the original vector, f
np.dot(eigvecs,A)

array([[0.24112461],
       [0.11243983],
       [0.09667273],
       [0.19998163],
       [0.69067789]])

In [87]:
# compare to f 
f

array([[0.24112461],
       [0.11243983],
       [0.09667273],
       [0.19998163],
       [0.69067789]])